### ISSUE TITLE
Simplificar o código no fobj.jl

### ISSUE THREAD

**Issue by CodeLenz** [diegoscmo/sheikra#2]
Em fobj.jl, 
  xmax   = size(anygrid,1)_gridsize
  ymax   = size(anygrid,2)_gridsize

Se não me engano, tinhamos colocado alguma outra coisa aqui, mais simples.

**Comment by diegoscmo** [comment]
Era isso aí mesmo. Antes estava escrito errado (um x/ymin estava sendo somado), por isso demorava muito.
