### ISSUE TITLE
Ponto Inicial

### ISSUE THREAD

**Issue by diegoscmo** [diegoscmo/sheikra#5]
Habilitar uma opção nas funções de otimização para receberem um ponto inicial ao invés de utilizar o Crazy_Joe.

**Comment by CodeLenz** [comment]
Fiz para o Powell2. Ele recebe p com valor default, [], que tem dimensão nula. Assim, se length(p)==0,
ele roda o crazy Joe, do contrário, testa para ver se o usuário inseriu um vetor coluna (dimensão 1 == 2*numturb).

**Comment by CodeLenz** [comment]
Faz sentido informar um ponto inicial para os outros métodos, já que todos dependem de uma população para começar ?

**Comment by diegoscmo** [comment]
O CMA-ES utiliza um ponto inicial também, esse ponto na verdade é utilizado para gerar uma distribuição estatística de lambda pontos com um desvio padrão sigma especificado. Vou aplicar a mesma lógica nele.

**Comment by CodeLenz** [comment]
Eu estava olhando isto agora mesmo.
